### ISSUE TITLE
Add Option for last like date/time to be shown

### ISSUE THREAD

**Issue by philpalmieri** [PartnerComm/wp-likes-plugin#5]
We would like to add the ability to store and optionally show the last liked date along with the like itself.

Please fork this repository and create a new branch 'feature/5-add-date', then submit a pull request when done.

# Requirements
- [ ]  All likes (add, not remove) should now record the date/time as the $prefix.'like_count' meta field (should probably be a timestamp)
- [ ] The shortcode should be updated so that if there is a flag 'show_date=true' the date of the last like should be displayed as a nested span tag in the display <span>
- [ ] add a unique class to the date span for 3rd party style/usage (styling optional)
- [ ] when a new like is added by a user, the displayed date/time should also update without page reload

**Comment by timbunch** [comment]
@philpalmieri
While I am in here looking around, there appears to be issues with the `'show_text'` attribute. Should this be on or off by default?
Also, is there a reason we aren't getting the ID server side instead of as an optional attribute in the shortcode?

**Comment by philpalmieri** [comment]
@timbunch, I believe it was intended to be off by default - for the ID, honestly I don't recall - it's been a while, but I will check when I get home tonight and review it... I *think it was because the UI is built in JS, so it's being built up post render, but I need to double check.

**Comment by philpalmieri** [comment]
Ok @timbunch it's coming back to me! - this is not meant to be an in-post-body shortcode, but just used in the templates... it definitly could be updated to be added into the body, but it was created to hook into custom layouts in loops for view partials - like a photo gallery or news feed, or custom content type, where the template would control the entire structure, not the wysiwyg - so we added a shortcode to drop into the template that renders the html target for the JS to take over on render.

An example: http://unumlearn.pcommstaging.com/ see the likes in the feed?  they are just partials rendered.

**Comment by philpalmieri** [comment]
An example: http://unumlearn.pcommstaging.com/ see the likes in the feed?  they are just partials rendered.

**Comment by timbunch** [comment]
Ah, that makes more sense then. I'll have an update headed you way now that I'm up to speed on that.

**Comment by philpalmieri** [comment]
no problem, i'll be online for a bit tonight too if you run into any issues.

**Comment by timbunch** [comment]
Is there any particular formatting of the date that is preferred?

**Comment by philpalmieri** [comment]
Lets use YYYY-MM-DD H:i:s so its query-able at some point and also should work with JS Date.parse()

**Comment by timbunch** [comment]
Ah. I was just adding a new DateTime to the DB, I was more curious about the front end display.

**Comment by philpalmieri** [comment]
Perfect - the front end format isnt as important at the moment, we can always change it
